# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dhmemi-patch-1" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: CJK-Fonts-Action
        # You may pin to the exact commit or the version.
        # uses: RisingInIris2017/cjk-fonts-action@651b49c1d36bef3a6039fd4cbe620e39bd36148a
        uses: RisingInIris2017/cjk-fonts-action@v1.0.7
      
      - name: Setup Typst
        # You may pin to the exact commit or the version.
        # uses: yusancky/setup-typst@bf23b5bbaead4a583e631c2823ce2b3569fa7d17
        uses: yusancky/setup-typst@v2.0.1

      - name: Compile typst file
        run: typst compile --font-path ./fonts resume.typ resume.pdf
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: dh-resume-cn.pdf
          # A file, directory or wildcard pattern that describes what to upload
          path: resume.pdf
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error # optional, default is warn
          # Duration after which artifact will expire in days. 0 means using default retention.
          retention-days: 15
